function [in_area] = in_membrane(x,y,z,G)
%[in_area] = in_membrane(x,y,z,G)

in_lower = (x >= G.Lex).*(x <= G.Lex + G.Lm).*(z >= G.Lez).*(z <= G.Lez + 2*G.Lm+G.Liz).*(y < G.Liy) + ...
    (x >= G.Lex + G.Lm + G.Lix).*(x <= G.Lex + 2*G.Lm + G.Lix).*(z >= G.Lez).*(z <= G.Lez + 2*G.Lm+G.Liz).*(y < G.Liy) + ...
    (z >= G.Lez).*(z <= G.Lez+G.Lm).*(x > G.Lex+G.Lm).*(x < G.Lex + G.Lm+G.Lix).*(y < G.Liy) + ...
    (z >= G.Lez + G.Lm + G.Liz).*(z <= G.Lez+2*G.Lm+ G.Liz).*(x > G.Lex+G.Lm).*(x < G.Lex + G.Lm+G.Lix).*(y < G.Liy) + ...
    (y >= G.Liy).*(y <= G.Liy+G.Lm).*(z >= G.Lez).*(z <= G.Lez + 2*G.Lm+G.Liz).*(x >= G.Lex).*(x <= G.Lex+2*G.Lm+G.Lix);

in_upper = (x >= G.Lex).*(x <= G.Lex + G.Lm).*(z >= G.Lez).*(z <= G.Lez + 2*G.Lm+G.Liz).*(y > G.Liy+G.L_cleft+2*G.Lm) + ...
    (x >= G.Lex + G.Lm + G.Lix).*(x <= G.Lex + 2*G.Lm + G.Lix).*(z >= G.Lez).*(z <= G.Lez + 2*G.Lm+G.Liz).*(y > G.Liy+G.L_cleft+2*G.Lm) + ...
    (z >= G.Lez).*(z <= G.Lez+G.Lm).*(x > G.Lex+G.Lm).*(x < G.Lex + G.Lm+G.Lix).*(y > G.Liy+G.L_cleft+2*G.Lm) + ...
    (z >= G.Lez + G.Lm + G.Liz).*(z <= G.Lez+2*G.Lm+ G.Liz).*(x > G.Lex+G.Lm).*(x < G.Lex + G.Lm+G.Lix).*(y > G.Liy+G.L_cleft+2*G.Lm) + ...
    (y >= G.Liy+G.L_cleft+G.Lm).*(y <= G.Liy+G.L_cleft+2*G.Lm).*(z >= G.Lez).*(z <= G.Lez + 2*G.Lm+G.Liz).*(x >= G.Lex).*(x <= G.Lex+2*G.Lm+G.Lix);

in_vesicle = (x >= G.Lex+G.Lm+(G.Lix-G.Lsv)/2-G.Lm).*(x <= G.Lex+G.Lm+(G.Lix-G.Lsv)/2).*(z >= G.Lez+G.Lm+(G.Liz-G.Lsv)/2-G.Lm).*(z <= G.Lez+G.Lm+(G.Liz+G.Lsv)/2+G.Lm).*(y > G.Liy+G.L_cleft+2*G.Lm).*(y < G.Liy+G.L_cleft+2*G.Lm+G.Lsv) + ...
    (x >= G.Lex+G.Lm+(G.Lix+G.Lsv)/2).*(x <= G.Lex+G.Lm+(G.Lix+G.Lsv)/2+G.Lm).*(z >= G.Lez+G.Lm+(G.Liz-G.Lsv)/2-G.Lm).*(z <= G.Lez+G.Lm+(G.Liz+G.Lsv)/2+G.Lm).*(y > G.Liy+G.L_cleft+2*G.Lm).*(y < G.Liy+G.L_cleft+2*G.Lm+G.Lsv) + ...
    (z >= G.Lez+G.Lm+(G.Liz-G.Lsv)/2-G.Lm).*(z <= G.Lez+G.Lm+(G.Liz-G.Lsv)/2).*(x >= G.Lex+G.Lm+(G.Lix-G.Lsv)/2-G.Lm).*(x <= G.Lex+G.Lm+(G.Lix+G.Lsv)/2+G.Lm).*(y > G.Liy+G.L_cleft+2*G.Lm).*(y < G.Liy+G.L_cleft+2*G.Lm+G.Lsv) + ...
    (z >= G.Lez+G.Lm+(G.Liz+G.Lsv)/2).*(z <= G.Lez+G.Lm+(G.Liz+G.Lsv)/2+G.Lm).*(x >= G.Lex+G.Lm+(G.Lix-G.Lsv)/2-G.Lm).*(x <= G.Lex+G.Lm+(G.Lix+G.Lsv)/2+G.Lm).*(y > G.Liy+G.L_cleft+2*G.Lm).*(y < G.Liy+G.L_cleft+2*G.Lm+G.Lsv) + ...
    (y >= G.Liy+G.L_cleft+2*G.Lm+G.Lsv).*(y <= G.Liy+G.L_cleft+2*G.Lm+G.Lsv+G.Lm).*(z >= G.Lez+G.Lm+(G.Liz-G.Lsv)/2-G.Lm).*(z <= G.Lez+G.Lm+(G.Liz+G.Lsv)/2+G.Lm).*(x >= G.Lex+G.Lm+(G.Lix-G.Lsv)/2-G.Lm).*(x <= G.Lex+G.Lm+(G.Lix+G.Lsv)/2+G.Lm);


in_area = in_lower + in_upper + in_vesicle;

end

